# Generated by Django 3.2.14 on 2022-07-25 13:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('adult_price', models.SmallIntegerField()),
                ('child_price', models.SmallIntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Book',
            new_name='Booking',
        ),
        migrations.RenameModel(
            old_name='Meals',
            new_name='Meal',
        ),
    ]
