# Generated by Django 3.2.14 on 2022-07-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=40)),
            ],
        ),
    ]
