# Generated by Django 3.2.14 on 2022-07-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment',
            field=models.IntegerField(choices=[('NP', 'Not Paid'), ('P', 'Payment Accepted')], default=0),
        ),
    ]
