# Generated by Django 3.2.14 on 2022-07-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_alter_booking_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment',
            field=models.CharField(choices=[('NP', 'Not Paid'), ('PA', 'Payment Accepted')], default='Not Paid', max_length=12),
        ),
    ]
