# Generated by Django 3.2.14 on 2022-08-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_alter_booking_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
