# Generated by Django 3.2.14 on 2022-08-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
