# Generated by Django 3.2.14 on 2022-08-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_remove_booking_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='booking_number'),
        ),
    ]
