# Generated by Django 3.2.14 on 2022-08-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_remove_booking_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='slug',
            field=models.SlugField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
