# Generated by Django 3.2.14 on 2022-08-08 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0023_remove_booking_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='reference_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
