# Generated by Django 3.2.14 on 2022-08-08 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0024_alter_booking_reference_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meal',
        ),
    ]
