# Generated by Django 3.2.14 on 2022-08-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0026_auto_20220808_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='adult_meat',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='adult_vegetarian',
            field=models.SmallIntegerField(blank=True),
        ),
    ]
