# Generated by Django 3.2.14 on 2022-08-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0027_auto_20220808_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='adult_meat',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='adult_vegetarian',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
