# Generated by Django 3.2.14 on 2022-08-11 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0033_booking_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='event',
        ),
    ]
