# Generated by Django 3.2.14 on 2022-08-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0034_remove_booking_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='adult_price',
            field=models.SmallIntegerField(default=150),
        ),
        migrations.AddField(
            model_name='booking',
            name='child_price',
            field=models.SmallIntegerField(default=100),
        ),
    ]
